spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: user
    password: pas
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
